"""add trace table

Revision ID: 3c5eeae6904b
Revises: f1dc32d0c5f1
Create Date: 2026-08-03 14:12:53.564439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5eeae6904b'
down_revision: Union[str, Sequence[str], None] = 'f1dc32d0c5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('request_text', sa.String(), nullable=False),
    sa.Column('agent_used', sa.String(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_id'), 'traces', ['id'], unique=False)
    op.create_index(op.f('ix_traces_owner_id'), 'traces', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traces_owner_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_id'), table_name='traces')
    op.drop_table('traces')
    # ### end Alembic commands ###
