"""add date_estimated to transactions

Revision ID: aa0d16fa7d94
Revises: 3c5eeae6904b
Create Date: 2026-08-04 12:07:50.216309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0d16fa7d94'
down_revision: Union[str, Sequence[str], None] = '3c5eeae6904b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'transactions',
        sa.Column('date_estimated', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'date_estimated')
    # ### end Alembic commands ###
